// blog index array
var index = [
  { "name"        : "Home",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  }/*, // duplicates below
   { "name"        : "Home 1",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 1",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 1",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 02",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 02",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 02",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 03",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 03",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 03",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 04",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 04",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 04",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 05",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 05",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 05",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 06",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 06",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 06",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 07",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 07",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 07",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 08",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 08",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 08",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 09",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 09",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 09",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  },
  { "name"        : "Home 10",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site.",
    "relevance"   : 0
  },
  { "name"        : "About 10",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site.",
    "relevance"   : 0
  },
  { "name"        : "Privacy Policy 10",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github.",
    "relevance"   : 0
  }*/
];
