"use strict";

// blog index array
const index = [
  { "name"        : "Home",
    "datetime"    : "2020-12-10 15:04-08:00",
    // "datetime" : new Date("2020-12-10 15:04:00-08:00"),
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  }, // duplicates below
  { "name"        : "Home 01",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 01",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 01",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 02",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 02",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 02",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 03",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 03",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 03",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 04",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 04",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 04",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 05",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 05",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 05",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 06",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 06",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 06",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 07",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 07",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 07",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 08",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 08",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 08",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 09",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 09",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 09",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  },
  { "name"        : "Home 10",
    "datetime"    : "2020-12-10 15:04-08:00",
    "url"         : "../index.html",
    "keywords"    : [ "home",
                      "david",
                      "kellogg"],
    "description" : "This is the home of the site."
  },
  { "name"        : "About 10",
    "datetime"    : "2020-12-24 08:54-08:00",
    "url"         : "../about.html",
    "keywords"    : [ "about",
                      "david",
                      "kellogg"],
    "description" : "This is the about page for the site."
  },
  { "name"        : "Privacy Policy 10",
    "datetime"    : "2020-12-20 20:53-08:00",
    "url"         : "../privacy-policy.html",
    "keywords"    : [ "privacy",
                      "policy",
                      "github"],
    "description" : "This is the privacy policy for this site and github."
  }
];
export default index
